### ISSUE TITLE
Why copy RLS packages to BucketFS

### ISSUE THREAD

**Issue by peterkioko** [exasol/row-level-security-lua#81]
Question:

The user guide states:

> Download the latest available release of Row Level Security to BucketFS.

Why is this step necessary? The next step says to paste the entire contents of the RLS lua code into the adapter script so it seems it's not pulling it from the BucketFS.

Wondering,
Peter

**Comment by redcatbear** [comment]
That must be a remnant from porting the document from Java RLS to Lua RLS. In the Java world the adapter is implemented in a JAR archive which needs to be uploaded to BucketFS before you can register the adapter script.

In the Lua case you are right, this is not necessary since the adapter script already contains everything you need. I am going to review the handbook and rework that passage for Lua RLS.

**Comment by redcatbear** [comment]
Fixed with PR #82.
